plugin.json
widget/templates/layouts/item-1.html
widget/templates/layouts/item-2.html

1. Added the backgroundAudio feature.
2. corrected font size of Title in Item page.

Fixed the issue #114697821.

---

widget/controllers/widget.home.controller.js

MEDIA CENTER MANUAL: Space for wysiwyg needs to collapse on the app when there is no content has been Fixed.

Fixed the issue: #115067479

---

control/content/app.js
control/content/assets/js/angular-csv.js
control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
control/content/templates/home.html
test/assets/buildfire.js
test/control/content/app.js
test/control/content/controller/content.home.controller.js
test/control/content/controller/content.media.controller.js
widget/controllers/widget.home.controller.js
widget/templates/layouts/now-playing.html

This pull request contains:
1.Implementation of breadcrumbs
2. Export CSV condition added for safari and shown a NOTE for it.
3. audio player does not load when tap on 'Listen' of 1st media file of any album.
4. Emulator does not show item details page when you are in the corresponding item in the editor.

Fixed the issues: #115390757, #114196707, #114990517

---

control/content/controllers/content.home.controller.js
control/design/controllers/design.home.controller.js

This pull request contains : 
Fixes to  prevent the save call when plugin loads initially.

Fixes to prevent save call when plugin loads initially.

---

control/content/controllers/content.home.controller.js
test/control/content/controller/content.home.controller.js

This pull request contains:
Fixed the issue related to breadcrumb(Home/pluginName/Item/item)

Breadcrumb related issue Fixed.

---

widget/assets/css/widget.app.css
widget/templates/modals/remove-track-modal.html

This pull request contains the fixes for issue: 
[GAT-BFI008-50] AppBuilding1: App Exclusives - Go to Playlist, Add to Playlist, Remove from Playlist and Purchase are not functioning.

Fixed the issue: #114196297

---

widget/controllers/widget.nowplaying.controller.js
widget/modals.js
widget/templates/layouts/now-playing.html
widget/templates/modals/remove-track-modal.html

1. MEDIA CENTERS AND AUDIO PLAYER: "Playlist" button should be white and say "Go to your playlist".
2. MEDIA CENTERS AND AUDIO PLAYER: More menu UI is messed up.
3. MEDIA CENTERS AND AUDIO PLAYER: When you click "Remove from playlist" you have to click the next popup SEVERAL times to clear it.

Fixed the issues: #116387953,#116387873 and #116387625.

---

widget/assets/css/widget.app.css
widget/controllers/widget.nowplaying.controller.js
widget/templates/layouts/now-playing.html

1. MEDIA CENTERS AND AUDIO PLAYER: "Playlist" button should be white and say "Go to your playlist".
2. MEDIA CENTERS AND AUDIO PLAYER: Progress bar does not look like High Fidelities.
3. Fixed the issue: When remove a track from playlist then next track have the remove button automatically.

Fixed the issues: #116387953 and #116566327.

---

widget/assets/css/widget.app.css
widget/templates/layouts/now-playing.html

1. make the bar thinner (max 3 pixels tall)
2. Remove the stroke from the circle
3. bring the time indicators closer to the progress bar (check HFs)
4. make the time indicators 60% opacity
5. make sure that the song title is the same font size as the title bar text
6.  make sure the artist name is the same size as Open Playlist

Fixed the issue: #116566327.

---

widget/templates/layouts/now-playing.html

1. MEDIA CENTERS AND AUDIO PLAYER: More menu UI is messed up.
2. When going to "..." to playlist  we show Cancel instead off Done.

Fixed the issues: #116387873 and #117032561.

---

widget/controllers/widget.home.controller.js

Transitions on widget side should be as follows : 
While opening an item : Right to left. 
While going back : Left to Right.

Made transitions consistent similar to other plugins, ticket : #116510275

---

widget/templates/layouts/now-playing.html

1. MEDIA CENTERS AND AUDIO PLAYER: More menu UI is messed up.
2. MEDIA CENTERS AND AUDIO PLAYER: Playlist UI is messed up.

Fixed the issues: #116387873 and #116387455.

---

package-lock.json
widget/app.js
widget/controllers/widget.home.controller.js

- https://app.asana.com/0/503101155812087/1164527916161945/f

Fixing deep linking issue

---

widget/controllers/widget.nowplaying.controller.js

https://app.asana.com/0/503101155812087/1197049855005953/f

Dropbox support

---

widget/app.js
widget/assets/css/widget.app.css
widget/controllers/widget.home.controller.js
widget/index.html
widget/templates/home.html

https://app.asana.com/0/503101155812087/1198971378771205/f

Deep Linking Fix

---

widget/assets/css/widget.app.css
widget/templates/layouts/item-1.html
widget/templates/layouts/item-2.html

https://app.asana.com/0/503101155812087/1199244023688552

hide sharing && source url temporary

---

widget/controllers/widget.media.controller.js

https://app.asana.com/0/503101155812087/1199394899274813/f

support src url for showing source icon

---

widget/assets/css/widget.app.css
widget/templates/layouts/item-1.html
widget/templates/layouts/item-2.html

https://app.asana.com/0/503101155812087/1199613745349405/f

More Options Feature Fixed

---

widget/assets/css/media.css
widget/templates/layouts/list-3.html

- Fix title overlap in layout 3 (https://app.asana.com/0/503101155812087/1199592601027696/f)

Fix title overlap in layout 3.

---

widget/controllers/widget.nowplaying.controller.js
widget/templates/layouts/now-playing.html

https://app.asana.com/0/503101155812087/1199880491741636/f
https://app.asana.com/0/503101155812087/1199712707725071/f

fixed: loop playlist, audio image over background

---

widget/controllers/widget.home.controller.js

https://buildfire.atlassian.net/jira/software/projects/PLUGINS/boards/26?selectedIssue=PLUGINS-153

Deeplinks Fix

---

control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
control/content/index.html
control/strings/app.js
control/strings/assets/css/control.strings.css
control/strings/assets/js/stringsUI.js
control/strings/controllers/strings.home.controller.js
control/strings/index.html
control/strings/templates/home.html
plugin.json
widget/app.js
widget/controllers/widget.home.controller.js
widget/controllers/widget.nowplaying.controller.js
widget/index.html
widget/js/shared/Deeplink.js
widget/js/shared/strings.js
widget/js/shared/stringsConfig.js
widget/modals.js
widget/templates/home.html
widget/templates/layouts/now-playing.html
widget/templates/modals/remove-track-modal.html

https://buildfire.atlassian.net/browse/PLUGINS-181?atlOrigin=eyJpIjoiYmM5NDZjZTYyMzRkNDg0YzgzMTFiZDY1YTY3MTUwMTciLCJwIjoiaiJ9

Deep Linking Enhancement

---

widget/controllers/widget.nowplaying.controller.js

https://buildfire.atlassian.net/browse/PLUGINS-268?atlOrigin=eyJpIjoiMWM3MTliMGY5Y2E4NDMwODliNjc0N2I2MTE2Nzg2M2MiLCJwIjoiaiJ9

Loop playlist fix

---

control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
control/content/services.js
widget/controllers/widget.home.controller.js
widget/services.js

https://buildfire.atlassian.net/browse/PLUGINS-250?atlOrigin=eyJpIjoiN2YzYTc4MDExN2QwNGZlZmEwMTM1OWJlNzA5ZmRjODMiLCJwIjoiaiJ9

alphabetical sort enhancement

---

widget/app.js
widget/controllers/widget.media.controller.js
widget/templates/layouts/item-1.html
widget/templates/layouts/item-2.html
widget/templates/layouts/video-player.html

**Ticket** https://buildfire.atlassian.net/browse/FEAT-21

enh: Android Landscape Enhancement

---

control/content/controllers/content.media.controller.js

**Ticket** https://buildfire.atlassian.net/browse/CS-233

dev: Saving Fixed

---

widget/controllers/widget.media.controller.js

**Ticket** https://buildfire.atlassian.net/browse/CS-598

IOS AutoPlay Fixed

---

control/content/controllers/content.home.controller.js
widget/controllers/widget.home.controller.js

https://buildfire.atlassian.net/browse/CS-705

fix: remove regex for better db perfomance

---

control/content/app.js
control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
control/content/index.html
control/content/mediaDateIndexing.js
control/content/services.js
control/design/controllers/design.home.controller.js
widget/controllers/widget.home.controller.js
widget/services.js

**Ticket** https://buildfire.atlassian.net/browse/CS-750

Media Date Indexing

---

control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js

https://buildfire.atlassian.net/browse/PT-1342

Deep link not created fix

---

control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
control/content/mediaDateIndexing.js
control/design/controllers/design.home.controller.js
widget/controllers/widget.home.controller.js

**Ticket** https://buildfire.atlassian.net/browse/PT-3265

DataCreated Indexed

---

widget/controllers/widget.home.controller.js

https://buildfire.atlassian.net/browse/PT-1317

fixed inner deeplinks

---

widget/controllers/widget.nowplaying.controller.js

JIRA ticket: https://buildfire.atlassian.net/browse/PT-4329

fixed Repeat button does not repeat audio

---

control/content/controllers/content.media.controller.js
widget/app.js
widget/controllers/widget.home.controller.js
widget/controllers/widget.media.controller.js
widget/downloadHandler.js
widget/js/data/offlineMedia.js
widget/js/shared/offlineAccess.js

https://buildfire.atlassian.net/browse/CS-887

added analytics for video downloads + download ui bug

---

widget/controllers/widget.home.controller.js
widget/templates/layouts/list-1.html
widget/templates/layouts/list-2.html
widget/templates/layouts/list-3.html
widget/templates/layouts/list-4.html

**Ticket**
https://buildfire.atlassian.net/browse/CS-704

Lazy Loading Fix

---

widget/templates/layouts/list-2.html
widget/templates/layouts/list-3.html
widget/templates/layouts/list-4.html

**Ticket** https://buildfire.atlassian.net/browse/CS-1169

Fixed Empty Box Not Hiding On Certain Layouts

---

widget/controllers/widget.home.controller.js

https://buildfire.atlassian.net/browse/PT-6389

fix syncing

---

control/content/controllers/content.home.controller.js

Add missing fields when importing and exporting CSV data

Fix template CSV, add missing fields

---

widget/controllers/widget.nowplaying.controller.js

- the audio can be played multi time

fix play audio several times

---

widget/app.js
widget/controllers/widget.home.controller.js
widget/controllers/widget.media.controller.js
widget/controllers/widget.nowplaying.controller.js
widget/downloadHandler.js
widget/js/data/offlineMedia.js
widget/js/shared/offlineAccess.js
widget/templates/layouts/now-playing.html

- Fix the white screen in offline mode "IOS"
- Fix playing downloaded audio in offline mode "IOS"
- Fix play audio from the playlist
- Fix playlist audio title and progress when playing
- Fix skip audio when enabling autoplay "CP-Setting"
- fix the white screen in IOS
- fix play playlist audio
- fix download audio on IOS

White screen offline download playlist fix

---

control/content/controllers/content.home.controller.js
control/content/controllers/content.media.controller.js
widget/assets/js/vg-vimeo-buildfire-edited.js
widget/controllers/widget.home.controller.js
widget/controllers/widget.media.controller.js
widget/controllers/widget.nowplaying.controller.js

- fix dropbox images URL for top and thumbnail images

fix missing media thumbnail 

---

widget/app.js
widget/controllers/widget.nowplaying.controller.js
widget/templates/layouts/now-playing.html

fix hidden playlist items when the current track is finished and the user is in the playlist view

Fix/hidden playlist - PLUG-2817

---

widget/controllers/widget.home.controller.js

avoid un-needed unregister deeplinks

fix(widget): avoid unregister deeplinks

---

widget/controllers/widget.nowplaying.controller.js

complete audio in the case user paused it from side menu

fix(widget): complete audio service - PLUG-3857

---

widget/controllers/widget.media.controller.js

enhance video title to include the case when it includes "

fix(widget): enhance video title

---

widget/services.js

Show youtube default controllers for youtube videos

Youtube Default Controllers
